// Auto-generated. Do not edit!

// (in-package autodock_core.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class AutoDockingGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.docking_waypoint = null;
    }
    else {
      if (initObj.hasOwnProperty('docking_waypoint')) {
        this.docking_waypoint = initObj.docking_waypoint
      }
      else {
        this.docking_waypoint = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type AutoDockingGoal
    // Serialize message field [docking_waypoint]
    bufferOffset = _serializer.string(obj.docking_waypoint, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type AutoDockingGoal
    let len;
    let data = new AutoDockingGoal(null);
    // Deserialize message field [docking_waypoint]
    data.docking_waypoint = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += _getByteLength(object.docking_waypoint);
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'autodock_core/AutoDockingGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '1166f30e9b74233e3cfce92a16969363';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    ######################################################################
    # GOAL
    ## docking waypoint heading to the charging station
    string docking_waypoint
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new AutoDockingGoal(null);
    if (msg.docking_waypoint !== undefined) {
      resolved.docking_waypoint = msg.docking_waypoint;
    }
    else {
      resolved.docking_waypoint = ''
    }

    return resolved;
    }
};

module.exports = AutoDockingGoal;
