(cl:defpackage autodock_core-msg
  (:use )
  (:export
   "<AUTODOCKINGACTION>"
   "AUTODOCKINGACTION"
   "<AUTODOCKINGACTIONFEEDBACK>"
   "AUTODOCKINGACTIONFEEDBACK"
   "<AUTODOCKINGACTIONGOAL>"
   "AUTODOCKINGACTIONGOAL"
   "<AUTODOCKINGACTIONRESULT>"
   "AUTODOCKINGACTIONRESULT"
   "<AUTODOCKINGFEEDBACK>"
   "AUTODOCKINGFEEDBACK"
   "<AUTODOCKINGGOAL>"
   "AUTODOCKINGGOAL"
   "<AUTODOCKINGRESULT>"
   "AUTODOCKINGRESULT"
  ))

