; Auto-generated. Do not edit!


(cl:in-package autodock_core-msg)


;//! \htmlinclude AutoDockingResult.msg.html

(cl:defclass <AutoDockingResult> (roslisp-msg-protocol:ros-message)
  ((is_success
    :reader is_success
    :initarg :is_success
    :type cl:boolean
    :initform cl:nil)
   (status
    :reader status
    :initarg :status
    :type cl:string
    :initform ""))
)

(cl:defclass AutoDockingResult (<AutoDockingResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <AutoDockingResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'AutoDockingResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name autodock_core-msg:<AutoDockingResult> is deprecated: use autodock_core-msg:AutoDockingResult instead.")))

(cl:ensure-generic-function 'is_success-val :lambda-list '(m))
(cl:defmethod is_success-val ((m <AutoDockingResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader autodock_core-msg:is_success-val is deprecated.  Use autodock_core-msg:is_success instead.")
  (is_success m))

(cl:ensure-generic-function 'status-val :lambda-list '(m))
(cl:defmethod status-val ((m <AutoDockingResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader autodock_core-msg:status-val is deprecated.  Use autodock_core-msg:status instead.")
  (status m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <AutoDockingResult>) ostream)
  "Serializes a message object of type '<AutoDockingResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'is_success) 1 0)) ostream)
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'status))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'status))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <AutoDockingResult>) istream)
  "Deserializes a message object of type '<AutoDockingResult>"
    (cl:setf (cl:slot-value msg 'is_success) (cl:not (cl:zerop (cl:read-byte istream))))
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'status) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'status) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<AutoDockingResult>)))
  "Returns string type for a message object of type '<AutoDockingResult>"
  "autodock_core/AutoDockingResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'AutoDockingResult)))
  "Returns string type for a message object of type 'AutoDockingResult"
  "autodock_core/AutoDockingResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<AutoDockingResult>)))
  "Returns md5sum for a message object of type '<AutoDockingResult>"
  "bfa9cf20c0611b957dcdbedc26407b4f")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'AutoDockingResult)))
  "Returns md5sum for a message object of type 'AutoDockingResult"
  "bfa9cf20c0611b957dcdbedc26407b4f")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<AutoDockingResult>)))
  "Returns full string definition for message of type '<AutoDockingResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%######################################################################~%# RESULT~%~%## if docking succeed~%bool is_success~%~%## verbose description of the result~%string status~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'AutoDockingResult)))
  "Returns full string definition for message of type 'AutoDockingResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%######################################################################~%# RESULT~%~%## if docking succeed~%bool is_success~%~%## verbose description of the result~%string status~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <AutoDockingResult>))
  (cl:+ 0
     1
     4 (cl:length (cl:slot-value msg 'status))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <AutoDockingResult>))
  "Converts a ROS message object to a list"
  (cl:list 'AutoDockingResult
    (cl:cons ':is_success (is_success msg))
    (cl:cons ':status (status msg))
))
