; Auto-generated. Do not edit!


(cl:in-package autodock_core-msg)


;//! \htmlinclude AutoDockingGoal.msg.html

(cl:defclass <AutoDockingGoal> (roslisp-msg-protocol:ros-message)
  ((docking_waypoint
    :reader docking_waypoint
    :initarg :docking_waypoint
    :type cl:string
    :initform ""))
)

(cl:defclass AutoDockingGoal (<AutoDockingGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <AutoDockingGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'AutoDockingGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name autodock_core-msg:<AutoDockingGoal> is deprecated: use autodock_core-msg:AutoDockingGoal instead.")))

(cl:ensure-generic-function 'docking_waypoint-val :lambda-list '(m))
(cl:defmethod docking_waypoint-val ((m <AutoDockingGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader autodock_core-msg:docking_waypoint-val is deprecated.  Use autodock_core-msg:docking_waypoint instead.")
  (docking_waypoint m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <AutoDockingGoal>) ostream)
  "Serializes a message object of type '<AutoDockingGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'docking_waypoint))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'docking_waypoint))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <AutoDockingGoal>) istream)
  "Deserializes a message object of type '<AutoDockingGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'docking_waypoint) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'docking_waypoint) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<AutoDockingGoal>)))
  "Returns string type for a message object of type '<AutoDockingGoal>"
  "autodock_core/AutoDockingGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'AutoDockingGoal)))
  "Returns string type for a message object of type 'AutoDockingGoal"
  "autodock_core/AutoDockingGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<AutoDockingGoal>)))
  "Returns md5sum for a message object of type '<AutoDockingGoal>"
  "1166f30e9b74233e3cfce92a16969363")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'AutoDockingGoal)))
  "Returns md5sum for a message object of type 'AutoDockingGoal"
  "1166f30e9b74233e3cfce92a16969363")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<AutoDockingGoal>)))
  "Returns full string definition for message of type '<AutoDockingGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%######################################################################~%# GOAL~%## docking waypoint heading to the charging station~%string docking_waypoint~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'AutoDockingGoal)))
  "Returns full string definition for message of type 'AutoDockingGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%######################################################################~%# GOAL~%## docking waypoint heading to the charging station~%string docking_waypoint~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <AutoDockingGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'docking_waypoint))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <AutoDockingGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'AutoDockingGoal
    (cl:cons ':docking_waypoint (docking_waypoint msg))
))
