// Generated by gencpp from file autodock_core/AutoDockingActionGoal.msg
// DO NOT EDIT!


#ifndef AUTODOCK_CORE_MESSAGE_AUTODOCKINGACTIONGOAL_H
#define AUTODOCK_CORE_MESSAGE_AUTODOCKINGACTIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <autodock_core/AutoDockingGoal.h>

namespace autodock_core
{
template <class ContainerAllocator>
struct AutoDockingActionGoal_
{
  typedef AutoDockingActionGoal_<ContainerAllocator> Type;

  AutoDockingActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  AutoDockingActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::autodock_core::AutoDockingGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::autodock_core::AutoDockingActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autodock_core::AutoDockingActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct AutoDockingActionGoal_

typedef ::autodock_core::AutoDockingActionGoal_<std::allocator<void> > AutoDockingActionGoal;

typedef boost::shared_ptr< ::autodock_core::AutoDockingActionGoal > AutoDockingActionGoalPtr;
typedef boost::shared_ptr< ::autodock_core::AutoDockingActionGoal const> AutoDockingActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autodock_core::AutoDockingActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autodock_core::AutoDockingActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::autodock_core::AutoDockingActionGoal_<ContainerAllocator1> & lhs, const ::autodock_core::AutoDockingActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::autodock_core::AutoDockingActionGoal_<ContainerAllocator1> & lhs, const ::autodock_core::AutoDockingActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace autodock_core

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::autodock_core::AutoDockingActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autodock_core::AutoDockingActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autodock_core::AutoDockingActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autodock_core::AutoDockingActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autodock_core::AutoDockingActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autodock_core::AutoDockingActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autodock_core::AutoDockingActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f18bf63ed7e62ff3a957a7b645860d30";
  }

  static const char* value(const ::autodock_core::AutoDockingActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf18bf63ed7e62ff3ULL;
  static const uint64_t static_value2 = 0xa957a7b645860d30ULL;
};

template<class ContainerAllocator>
struct DataType< ::autodock_core::AutoDockingActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autodock_core/AutoDockingActionGoal";
  }

  static const char* value(const ::autodock_core::AutoDockingActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autodock_core::AutoDockingActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"AutoDockingGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: autodock_core/AutoDockingGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"######################################################################\n"
"# GOAL\n"
"## docking waypoint heading to the charging station\n"
"string docking_waypoint\n"
"\n"
;
  }

  static const char* value(const ::autodock_core::AutoDockingActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autodock_core::AutoDockingActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AutoDockingActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autodock_core::AutoDockingActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autodock_core::AutoDockingActionGoal_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "goal_id: ";
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "goal: ";
    Printer< ::autodock_core::AutoDockingGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTODOCK_CORE_MESSAGE_AUTODOCKINGACTIONGOAL_H
