// Generated by gencpp from file autodock_core/AutoDockingActionFeedback.msg
// DO NOT EDIT!


#ifndef AUTODOCK_CORE_MESSAGE_AUTODOCKINGACTIONFEEDBACK_H
#define AUTODOCK_CORE_MESSAGE_AUTODOCKINGACTIONFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalStatus.h>
#include <autodock_core/AutoDockingFeedback.h>

namespace autodock_core
{
template <class ContainerAllocator>
struct AutoDockingActionFeedback_
{
  typedef AutoDockingActionFeedback_<ContainerAllocator> Type;

  AutoDockingActionFeedback_()
    : header()
    , status()
    , feedback()  {
    }
  AutoDockingActionFeedback_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , status(_alloc)
    , feedback(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalStatus_<ContainerAllocator>  _status_type;
  _status_type status;

   typedef  ::autodock_core::AutoDockingFeedback_<ContainerAllocator>  _feedback_type;
  _feedback_type feedback;





  typedef boost::shared_ptr< ::autodock_core::AutoDockingActionFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autodock_core::AutoDockingActionFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct AutoDockingActionFeedback_

typedef ::autodock_core::AutoDockingActionFeedback_<std::allocator<void> > AutoDockingActionFeedback;

typedef boost::shared_ptr< ::autodock_core::AutoDockingActionFeedback > AutoDockingActionFeedbackPtr;
typedef boost::shared_ptr< ::autodock_core::AutoDockingActionFeedback const> AutoDockingActionFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autodock_core::AutoDockingActionFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autodock_core::AutoDockingActionFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::autodock_core::AutoDockingActionFeedback_<ContainerAllocator1> & lhs, const ::autodock_core::AutoDockingActionFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.status == rhs.status &&
    lhs.feedback == rhs.feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::autodock_core::AutoDockingActionFeedback_<ContainerAllocator1> & lhs, const ::autodock_core::AutoDockingActionFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace autodock_core

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::autodock_core::AutoDockingActionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autodock_core::AutoDockingActionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autodock_core::AutoDockingActionFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autodock_core::AutoDockingActionFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autodock_core::AutoDockingActionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autodock_core::AutoDockingActionFeedback_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autodock_core::AutoDockingActionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3c87c1a08a9477d780a74ec3b7d51d7f";
  }

  static const char* value(const ::autodock_core::AutoDockingActionFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3c87c1a08a9477d7ULL;
  static const uint64_t static_value2 = 0x80a74ec3b7d51d7fULL;
};

template<class ContainerAllocator>
struct DataType< ::autodock_core::AutoDockingActionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autodock_core/AutoDockingActionFeedback";
  }

  static const char* value(const ::autodock_core::AutoDockingActionFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autodock_core::AutoDockingActionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"AutoDockingFeedback feedback\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalStatus\n"
"GoalID goal_id\n"
"uint8 status\n"
"uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n"
"uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n"
"uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n"
"                            #   and has since completed its execution (Terminal State)\n"
"uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n"
"uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n"
"                            #    to some failure (Terminal State)\n"
"uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n"
"                            #    because the goal was unattainable or invalid (Terminal State)\n"
"uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n"
"                            #    and has not yet completed execution\n"
"uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n"
"                            #    but the action server has not yet confirmed that the goal is canceled\n"
"uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n"
"                            #    and was successfully cancelled (Terminal State)\n"
"uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n"
"                            #    sent over the wire by an action server\n"
"\n"
"#Allow for the user to associate a string with GoalStatus for debugging\n"
"string text\n"
"\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: autodock_core/AutoDockingFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"######################################################################\n"
"# FEEDBACK\n"
"\n"
"## progress approx, 0 - 1.0 \n"
"float32 progress\n"
"\n"
"## verbose description of the progress\n"
"string status\n"
"\n"
"## state\n"
"uint8 STATE_INVALID = 0\n"
"uint8 STATE_IDLE = 1\n"
"uint8 STATE_PREDOCK = 2\n"
"uint8 STATE_PARALLEL_CORRECTION = 3\n"
"uint8 STATE_STEER_DOCK = 4\n"
"uint8 STATE_LAST_MILE = 5\n"
"uint8 STATE_ACTIVATE_CHARGER = 6\n"
"uint8 STATE_RETRY = 7\n"
"uint8 STATE_PAUSE = 8\n"
"\n"
"uint8 state\n"
"\n"
;
  }

  static const char* value(const ::autodock_core::AutoDockingActionFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autodock_core::AutoDockingActionFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.status);
      stream.next(m.feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AutoDockingActionFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autodock_core::AutoDockingActionFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autodock_core::AutoDockingActionFeedback_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "status: ";
    Printer< ::actionlib_msgs::GoalStatus_<ContainerAllocator> >::stream(s, indent + "  ", v.status);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "feedback: ";
    Printer< ::autodock_core::AutoDockingFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTODOCK_CORE_MESSAGE_AUTODOCKINGACTIONFEEDBACK_H
