// Generated by gencpp from file autodock_core/AutoDockingResult.msg
// DO NOT EDIT!


#ifndef AUTODOCK_CORE_MESSAGE_AUTODOCKINGRESULT_H
#define AUTODOCK_CORE_MESSAGE_AUTODOCKINGRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace autodock_core
{
template <class ContainerAllocator>
struct AutoDockingResult_
{
  typedef AutoDockingResult_<ContainerAllocator> Type;

  AutoDockingResult_()
    : is_success(false)
    , status()  {
    }
  AutoDockingResult_(const ContainerAllocator& _alloc)
    : is_success(false)
    , status(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _is_success_type;
  _is_success_type is_success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::autodock_core::AutoDockingResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autodock_core::AutoDockingResult_<ContainerAllocator> const> ConstPtr;

}; // struct AutoDockingResult_

typedef ::autodock_core::AutoDockingResult_<std::allocator<void> > AutoDockingResult;

typedef boost::shared_ptr< ::autodock_core::AutoDockingResult > AutoDockingResultPtr;
typedef boost::shared_ptr< ::autodock_core::AutoDockingResult const> AutoDockingResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autodock_core::AutoDockingResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autodock_core::AutoDockingResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::autodock_core::AutoDockingResult_<ContainerAllocator1> & lhs, const ::autodock_core::AutoDockingResult_<ContainerAllocator2> & rhs)
{
  return lhs.is_success == rhs.is_success &&
    lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::autodock_core::AutoDockingResult_<ContainerAllocator1> & lhs, const ::autodock_core::AutoDockingResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace autodock_core

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::autodock_core::AutoDockingResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autodock_core::AutoDockingResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autodock_core::AutoDockingResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autodock_core::AutoDockingResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autodock_core::AutoDockingResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autodock_core::AutoDockingResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autodock_core::AutoDockingResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bfa9cf20c0611b957dcdbedc26407b4f";
  }

  static const char* value(const ::autodock_core::AutoDockingResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbfa9cf20c0611b95ULL;
  static const uint64_t static_value2 = 0x7dcdbedc26407b4fULL;
};

template<class ContainerAllocator>
struct DataType< ::autodock_core::AutoDockingResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autodock_core/AutoDockingResult";
  }

  static const char* value(const ::autodock_core::AutoDockingResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autodock_core::AutoDockingResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"######################################################################\n"
"# RESULT\n"
"\n"
"## if docking succeed\n"
"bool is_success\n"
"\n"
"## verbose description of the result\n"
"string status\n"
"\n"
;
  }

  static const char* value(const ::autodock_core::AutoDockingResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autodock_core::AutoDockingResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.is_success);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AutoDockingResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autodock_core::AutoDockingResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autodock_core::AutoDockingResult_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "is_success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_success);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTODOCK_CORE_MESSAGE_AUTODOCKINGRESULT_H
